In [2]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import mutual_info_score
from sklearn.neighbors import NearestNeighbors, ball_tree, BallTree
import time
from scipy.special import psi
import numpy as np
from universal_divergence import estimate


In [8]:
def kl_psi(x,y):
    n = len(x)
    m = len(y)
    nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(x)
    rau, _ = nbrs.kneighbors(x)
    nbrs = NearestNeighbors(n_neighbors=1, algorithm='ball_tree').fit(y)
    nu, _ = nbrs.kneighbors(x)
    rau =rau[:,1]
    nu = nu[:,0]
    
    epsilon = np.max(np.stack([rau,nu]),axis=0)
    # cd de voisins X (Y) pour chaque x(i) dans la boule epsilon(i)

    tree = BallTree(x, leaf_size=2)     
    l = tree.query_radius(x, r=epsilon, count_only=True)

    tree = BallTree(y, leaf_size=2)     
    k = tree.query_radius(x, r=epsilon, count_only=True)

    k[k==0]=1
    
    kl = 2*(1/n)*sum(np.log(nu)/np.log(rau)) + np.log(m/(n-1))+np.mean(psi(l)-psi(k))
    return kl

In [34]:
n = len(x)
m = len(y)
tree = BallTree(x, leaf_size=2)              
dist, ind = tree.query(x, k=2)
ro = dist[:,1]
tree = BallTree(y, leaf_size=2)              
nu, ind = tree.query(x, k=1)
nu=nu[:,0]
kl = 2*(1/n)*sum(np.log(nu)/np.log(ro)) + np.log(m/(n-1))
kl


2.0874227041857467

In [33]:
nu[:,0].shape

(5000,)

In [ ]:
JSD = 0.5*kl_psi(x,m)+kl_psi(x_m)

In [15]:
mean = [0, 0]
cov = [[1, 0], [0, 10]]
x = np.random.multivariate_normal(mean, cov, 5000)
y = np.random.multivariate_normal(mean, cov, 5000)
print(estimate(x, y,k=3))  # will be close to 0.0

mean2 = [10, 0]
cov2 = [[5, 0], [0, 5]]
z = np.random.multivariate_normal(mean2, cov2, 1000)
print(estimate(x, z,k=3))  # will be bigger than 0.0

0.010083882175194998
6.2723083279698155


In [36]:
estimate(x, y,k=3)

0.008828997012218698

In [12]:
mean = [0, 0]
cov = [[1, 0], [0, 10]]
x = np.random.multivariate_normal(mean, cov, 1000)
y = np.random.multivariate_normal(mean, cov, 1000)
print(kl_psi(x,y))

mean2 = [10, 0]
cov2 = [[5, 0], [0, 5]]
z = np.random.multivariate_normal(mean2, cov2, 1000)
print(kl_psi(x,z))


2.8022839853243093
5.302964029824913


In [189]:
begin = time.time()
n = len(x)
m = len(y)
nbrs = NearestNeighbors(n_neighbors=2, algorithm='brute').fit(x)
rau, _ = nbrs.kneighbors(x)
nbrs = NearestNeighbors(n_neighbors=1, algorithm='brute').fit(y)
nu, _ = nbrs.kneighbors(x)
rau =rau[:,1]
nu = nu[:,0]
kl = 2*(1/n)*sum(np.log(nu)/np.log(rau)) + np.log(m/(n-1))


In [190]:
epsilon = np.max(np.stack([rau,nu]),axis=0)
# cd de voisins X (Y) pour chaque x(i) dans la boule epsilon(i)

tree = BallTree(x, leaf_size=2)     
l = tree.query_radius(x, r=epsilon, count_only=True)

tree = BallTree(y, leaf_size=2)     
k = tree.query_radius(x, r=epsilon, count_only=True)

k[k==0]=1


In [191]:
kl = 2*(1/n)*sum(np.log(nu)/np.log(rau)) + np.log(m/(n-1))+np.mean(psi(l)-psi(k))


In [198]:
kl_psi(x,y)

7.049245327380758

In [ ]:
>>> import numpy as np
>>> np.random.seed(0)
>>> X = np.random.random((10, 3))  # 10 points in 3 dimensions
>>> tree = BallTree(X, leaf_size=2)     
>>> print(tree.query_radius(X[0], r=0.3, count_only=True))
3
>>> ind = tree.query_radius(X[0], r=0.3)  
>>> print(ind)  # indices of neighbors within distance 0.3
[3 0 1]

array([2, 1, 1, 2, 1, 2, 2, 2, 2, 3, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2,
       2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 2,
       1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 2,
       2, 1, 1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 1, 2,
       1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 2, 2, 2, 2, 3, 2, 1, 2, 2, 2, 2,
       2, 4, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       2, 1, 2, 1, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 2, 1, 1, 1, 1, 1, 2, 2, 2, 1, 2, 2, 1, 2, 3, 2, 2, 1, 2, 1, 2,
       2, 2, 2, 2, 2, 1, 2, 2, 1, 2, 4, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 1,
       1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 2, 2, 1, 1, 2, 1,
       1, 2, 2, 2, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1,
       1, 2, 2, 2, 1, 1, 1, 1, 1, 2, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 1, 1,
       2, 1, 3, 2, 1, 2, 1, 2, 2, 1, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2,
       1, 1, 2, 1, 1, 1, 2, 2, 1, 3, 2, 2, 1, 2, 2,

In [149]:
x.shape

(1000, 2)

In [94]:
np.mean(np.divide(np.log(nu),np.log(rau)))

1.081731627958029

In [95]:
np.log(m/(n-1))

0.00020002000266702272

In [96]:
m/(n-1)

1.0002000400080016

In [103]:
def kl_divergence(x,y):
    n = len(x)
    m = len(y)
    nbrs = NearestNeighbors(n_neighbors=2, algorithm='ball_tree').fit(x)
    rau, _ = nbrs.kneighbors(x)
    nbrs = NearestNeighbors(n_neighbors=1, algorithm='ball_tree').fit(y)
    nu, _ = nbrs.kneighbors(x)
    rau =rau[:,1]
    kl = 2*np.mean(np.divide(np.log(nu),np.log(rau))) + np.log(m/(n-1))
    return kl

In [104]:
begin = time.time()
print('estimated kl:', kl_divergence(x,z) , '     time:', time.time()-begin)

estimated kl: -0.3677980176329604      time: 1.3869824409484863


In [122]:
begin = time.time()

print('kl',estimate(x, y, k=None, n_jobs=1),'time',time.time()-begin)

kl -0.02628428776265701 time 88.99523067474365


In [8]:
def nn_kl(x,y, n_neighbors=1):
    n = len(x)
    m = len(y)
    '''
    x: samples of the reference density, y: samples approximated distribution
    '''
    nbrs = NearestNeighbors(n_neighbors=1, algorithm='ball_tree').fit(x)
    nu, _ = nbrs.kneighbors(y)
    nbrs = NearestNeighbors(n_neighbors=1, algorithm='ball_tree').fit(y)
    rau, _ = nbrs.kneighbors(x)
    
    kl = 2/n * np.sum(np.log(nu/rau))+np.log(m/n-1)
    return np.mean((distances))


In [18]:
n = len(x)
m = len(y)
nbrs = NearestNeighbors(n_neighbors=1, algorithm='ball_tree').fit(x)
nu, _ = nbrs.kneighbors(y)
nbrs = NearestNeighbors(n_neighbors=1, algorithm='ball_tree').fit(y)
rau, _ = nbrs.kneighbors(x)


In [15]:
rau.shape

(100, 1)

In [16]:
nu.shape

(4000, 1)

In [2]:
import numpy as np

In [4]:
np.load('testouille.npy')

array([0. , 0.5, 1. ])